### ISSUE TITLE
Use nested dicts as index

### ISSUE THREAD

**Issue by Peter9192** [eucp-project/storyboards#12]
Currently we have index.yaml and usecaseItems.md. Both are index files, used to register some summary information about our usecases.

It would be nice to merge the two into once. It could probably be something like

```yaml
usecase_name1:
  id: 0
  headline: EUCP example use case
  subtitle: Jane Doe et al., Ministry of Love
  static_folder: ~/static/usecase_0/
usecase_name2:
  id: 2
  ...
```
